name: Encuesta-App-Angular

on:
  push:
    branches:
    - main

jobs:
  desplegar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar tests
      run: npm run test:headless

    - name: Construir
      run: npm run build:prod

    - name: Desplegar
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/encuesta-app-angular
        enable_jekyll: true
