export interface TiposEncuesta {
  codigo?: any,
  codigo_ant?: any,
  codigo_cia?: any,
  codigo_cia_ant?: any,
  identificador?: any,
  identificador_ant?: any,
  descripcion?: any,
  afectacion?: any,
  createdIp?: any,
  createdAt?: any,
  updatedIp?: any,
  updatedAt?: any,
  companias?: any,
  admins?: any,
  encuestas?: any,
}
