name: Encuesta-App-Angular

on:
  push:
    branches:
    - main

jobs:
  desplegar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar Dependencias del package.lock
      run: npm install

    - name: Ejecutar tests de Angular
      run: npm run test:headless

    - name: Construir Aplicacion de Angular
      run: npm run build:prod

    - name: Desplegar en GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /
        enable_jekyll: false
        publish_branch: main

